version: '3'

services:
  pypy3:
    image: pypy:3
    container_name: pypy
    volumes:
      - ./app/:/app
    working_dir: /app
    tty: true
    command: >
      bash -c "pip install -r requirements.txt && bash"
    